### ISSUE TITLE
tty & stdin AKA launch rtorrent and STOPSIGNAL

### ISSUE THREAD

**Issue by fulminemizzega** [chamunks/alpine-rtorrent#2]
Hi,
I'm rolling my own version of alpine-rtorrent and googling "docker-compose rtorrent" I found your repo. My setup is similar to yours, I also run rtorrent as PID1 inside the container. To make it work, you need to add 
```
stdin_open: false
tty: false
```
to docker-compose.yml (which makes it as if you run docker run -it ...), see the [docs](https://docs.docker.com/compose/compose-file/#/cpu-shares-cpu-quota-cpuset-domainname-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-shm-size-stdin-open-tty-user-working-dir).
Then docker-compose up -d works fine.
Also check this: [rtorrent wiki](https://github.com/rakshasa/rtorrent/wiki/User-Guide#signal-handlers) or the wonderful [Gentoo wiki rtorrent page](https://wiki.gentoo.org/wiki/RTorrent#Controlling_rTorrent_exit), I prefer adding `STOPSIGNAL SIGINT` at the end of the rtorrent Dockerfile.

**Comment by chamunks** [comment]
If you're interested in doing so, I'd suggest making a PR.  I just make these for fun sometimes.  Realistically if I was smarter I would be running this app in its own sub user but I was kind of lazy when I built it.

~Closing the ticket as I've responded feel free to leave a response I will be sure to check it.
